apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: analyzer
  name: analyzer
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: analyzer
    spec:
      containers:
      - image: reportportal/service-analyzer:4.3.0
        name: analyzer
        resources: {}
      restartPolicy: Always
status: {}
