apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: jira
  name: jira
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: jira
    spec:
      containers:
      - env:
        - name: RP_PROFILES
          value: docker
        image: reportportal/service-jira:4.3.0
        name: jira
        resources: {}
      restartPolicy: Always
status: {}
