apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: registry
  name: registry
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: registry
    spec:
      containers:
      - args:
        - agent
        - -server
        - -bootstrap-expect=1
        - -ui
        - -client
        - 0.0.0.0
        env:
        - name: CONSUL_LOCAL_CONFIG
          value: '{"leave_on_terminate": true}'
        image: consul:1.0.6
        name: registry
        ports:
        - containerPort: 8500
        resources: {}
        volumeMounts:
        - mountPath: /consul/data
          name: registry-claim0
      restartPolicy: Always
      volumes:
      - name: registry-claim0
        persistentVolumeClaim:
          claimName: registry-claim0
status: {}
